apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/etc/otelcol/config.yaml"]
          ports:
            - { name: prometheus, containerPort: {{ .Values.service.prometheusPort }} }
          volumeMounts:
            - { name: config, mountPath: /etc/otelcol }
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
